services:
  # Utility service for running composer, provides a local volume for storing access tokens
  # https://hub.docker.com/_/composer
  composer:
    image: composer:2.8
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      COMPOSER_HOME: /.composer
    volumes:
      - ./:/app
      - ~/.composer:/.composer
    command: install

  # https://hub.docker.com/r/ideasonpurpose/phpunit-watch
  test:
    # image: ideasonpurpose/phpunit-watch:dev
    image: ideasonpurpose/phpunit-watch:1.4
    volumes:
      - ./:/app
